# Generated by Django 2.2.4 on 2021-06-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_auto_20210629_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='No notes to add.'),
        ),
    ]
